version: '2'
services:
    tripplanning-app:
        image: tripplanning
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tripplanning-postgresql:5432/TripPlanning
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tripplanning-postgresql:
        extends:
            file: postgresql.yml
            service: tripplanning-postgresql
